# Generated by Django 3.0.2 on 2020-04-05 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('empty', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=0)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='Plan.Semester')),
            ],
            options={
                'ordering': ['semester__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='Plan.Group')),
            ],
            options={
                'ordering': ['group__semester__name', 'group__name', 'date'],
                'unique_together': {('group', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('empty', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('teacher', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('place', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('class_type', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('class_index', models.CharField(blank=True, default=None, max_length=1, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='Plan.Day')),
            ],
            options={
                'ordering': ['day__group__semester__name', 'day__group__name', 'day__date', 'index'],
                'unique_together': {('day', 'index')},
            },
        ),
    ]
