# Generated by Django 3.0.2 on 2020-04-03 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('empty', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='Plan.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=10)),
                ('index', models.IntegerField()),
                ('empty', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('teacher', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('place', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('class_type', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('class_index', models.IntegerField(blank=True, default=None, null=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='Plan.Semester')),
            ],
            options={
                'ordering': ['date', 'index'],
                'unique_together': {('semester', 'date', 'index')},
            },
        ),
    ]
