# Generated by Django 3.0.2 on 2020-04-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='empty',
        ),
        migrations.RemoveField(
            model_name='group',
            name='empty',
        ),
    ]
