# Generated by Django 3.0.2 on 2020-04-06 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0002_auto_20200405_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='Plan.Group'),
        ),
    ]
