# Generated by Django 3.0.2 on 2020-04-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0003_auto_20200406_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
            ],
        ),
    ]
