# Generated by Django 3.0.2 on 2020-04-18 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0004_version'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Version',
        ),
    ]
