# Generated by Django 3.0.2 on 2020-04-19 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apk',
            name='apk',
            field=models.FileField(upload_to='media/apk'),
        ),
        migrations.CreateModel(
            name='ReleaseNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('apk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_notes', to='home.Apk')),
            ],
        ),
    ]
