# Generated by Django 3.0.2 on 2020-04-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200419_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apk',
            options={'ordering': ['-release_date']},
        ),
        migrations.AlterField(
            model_name='apk',
            name='version',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
